version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: dlp-postgres
    environment:
      POSTGRES_DB: ai_tlsdlp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ai_tlsdlp"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: dlp-network
